name: web_mercator
description: Dart implementation of the uber @math.gl/web-mercator javascript module.
version: 0.9.1-dev.1
homepage: https://github.com/nadous/dart-web-mercator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ">=1.1.1 <2.0.0"
  vector_math: "^2.0.8"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter